name: star-wars
services:
  mysql:
    image: mysql:8.4
    container_name: star-wars-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starwars
      MYSQL_USER: starwars
      MYSQL_PASSWORD: starwars
    ports:
      - "3366:3306"
    volumes:
      - ./.mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - star-wars

  api:
    build:
      context: ./star-wars-api
      dockerfile: Dockerfile
    container_name: star-wars-api
    working_dir: /var/www/html
    volumes:
      - ./star-wars-api:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8800:8000"
    networks:
      - star-wars

  web:
    build:
      context: ./star-wars-web
      dockerfile: Dockerfile
    container_name: star-wars-web
    working_dir: /app
    volumes:
      - ./star-wars-web:/app
      - ./star-wars-web/node_modules:/app/node_modules
      - ./star-wars-web/.next:/app/.next
    ports:
      - "8900:8100"
    depends_on:
      - api
    networks:
      - star-wars

networks:
  star-wars:

